name: build

on:
  push:
    branches:
      - fabric-26.2-build
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'microsoft'

      - name: Set up Gradle 9.5.1
        uses: gradle/actions/setup-gradle@v5
        with:
          gradle-version: '9.5.1'

      - name: Build Beyond Realms
        run: gradle build --stacktrace

      - name: Upload mod jars
        uses: actions/upload-artifact@v7
        with:
          name: BeyondRealms-26.2
          path: build/libs/*.jar
